---
name: Checks

on: [push]

jobs: 
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
      - name: Create .env file
        run: cp .env.sample .env
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: docker-compose run --rm alchubeth-recipes-app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker-compose run --rm alchubeth-recipes-app sh -c "flake8"